etingof/pyasn1

pyasn1/codec/ber/decoder.py
test/codec/ber/test_decoder.py

Make code like:
decoder.decode(some_data, asn1Spec=SomeType)
raise a better error message (you want SomeType() instead) instead of previous
one (about unbound get_tag() on SomeType).

Better error reporting with wrong spec

---

pyasn1/type/univ.py
test/type/test_univ.py

Add a helper for use with BitString. In most real-world cases bitstrings will
have a length that's a multiple of 8. Especially in crypto-related use.
Since you can already provide a value like '1234'H to initialise bitstrings,
create a matching serialiser which will give hex output.

Add a toHexString to BitString

---

pyasn1/codec/ber/decoder.py

Separating this PR as #5 has some other issues, but this one should be mergable by itself.  An example of the cache failure is in #5 as well.

handle non-caching of long tags properly

---

pyasn1/type/base.py

sphinx.ext.napoleon uses '__objclass__', 'im_class' on py2 instead of '__qualname__'.

fix doc creation on py2

---

pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/debug.py
pyasn1/type/base.py
pyasn1/type/constraint.py
pyasn1/type/namedtype.py
pyasn1/type/namedval.py
pyasn1/type/tag.py
pyasn1/type/tagmap.py

Old style classes prohibits using of, for example,
typing.cast(Sequence[X509Sequence], ...) casting, which checks whether
X509Sequence is a "type" (old style classes have "classobj" type).

Use new style classes, instead of an old ones

---

CHANGES.txt
pyasn1/type/namedtype.py

Following up [this issue](https://github.com/etingof/pyasn1/pull/12).

Fix to NamedTypes methods to handle .getTagMap() returning None

---

pyasn1/type/base.py
test/type/test_univ.py

Adding `__sizeof__` to skipped methods to fix #17

Fixing issue #17 by adding support for __sizeof__ for NoValue

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/encoder.py
pyasn1/codec/native/encoder.py
pyasn1/type/base.py
pyasn1/type/namedtype.py
pyasn1/type/univ.py
tests/codec/ber/test_decoder.py
tests/codec/ber/test_encoder.py
tests/codec/cer/test_encoder.py
tests/codec/der/test_encoder.py
tests/type/test_univ.py

* .getComponent*() changed to lazily instantiate underlying type on first read access
* SetOf/SequenceOf types can not have "holes" anymore
* optional/default components of constructed types refactored for better efficiency and flexibility.

Automatically instantiate constructed types components

---

pyasn1/type/univ.py

```
class KeyUsage(BitString):
namedValues = NamedValues(
('digitalSignature', 0),
('nonRepudiation', 1),
('keyEncipherment', 2),
('dataEncipherment', 3),
('keyAgreement', 4),
('keyCertSign', 5),
('cRLSign', 6),
('encipherOnly', 7),
('decipherOnly', 8),
)
encode(KeyUsage('keyCertSign,cRLSign')) != encode(KeyUsage("'0000011'B"))
^^
||
bit #5 -------------+|
bit #6 --------------+
```

Fix BitString initialization via namedValues

---

.gitignore
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/codec/native/decoder.py
pyasn1/codec/native/encoder.py

This PR moves the logger object in tight loops into local scopes to save on namespaces traversal.

Move logger calls into local scope

---

CHANGES.rst
doc/source/docs/type/useful/generalizedtime.rst
doc/source/docs/type/useful/utctime.rst
pyasn1/type/useful.py
tests/type/__main__.py
tests/type/test_useful.py

This PR introduces .asDateTime property and .toDateTime() method to GeneralizedTime and UTCTime classes. The goal is to ease ASN.1 time types <-> Python date time conversion.

Time types datetime support

---

CHANGES.rst
doc/source/docs/api-reference.rst
doc/source/docs/type/namedval/contents.rst
doc/source/docs/type/namedval/namedval.rst
pyasn1/type/namedval.py
pyasn1/type/univ.py
tests/type/test_namedval.py

This PR refactors the NamedValues class to mock Python dict and makes NamedValues instances accessible as a property of ASN.1 type.

NamedValues refactoring 

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/type/base.py
pyasn1/type/namedtype.py
pyasn1/type/namedval.py
pyasn1/type/tagmap.py
pyasn1/type/univ.py
pyasn1/type/unnamedtype.py
tests/type/test_namedtype.py
tests/type/test_univ.py

This PR refactors `.componentType` attribute of constructed ASN.1 types into a read-only property (like all other ASN.1-related attributes).
By way of doing this, the `SetOf/SequenceOf.componentType` becomes a container holding single ASN.1 type denoting the only field of the type.

.componentType as a property

---

pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/encoder.py
pyasn1/codec/native/decoder.py
pyasn1/codec/native/encoder.py
pyasn1/type/base.py
pyasn1/type/univ.py
tests/type/test_univ.py

This PR is a follow up to https://github.com/etingof/pyasn1/pull/46 which turned out to be incomplete and not fully functional.
This PR hopefully fixes that, specifically by reliably wrapping SequenceOf/SetOf.componentType into a container at the class creation phase.

.componentType as a property follow up

---

pyasn1/compat/binary.py
pyasn1/compat/calling.py
pyasn1/compat/dateandtime.py
pyasn1/compat/integer.py
pyasn1/compat/string.py
pyasn1/type/base.py
pyasn1/type/useful.py

This PR addresses a couple of bugs that only show up with older Pythons. Specifically:
* missing datetime.strptime()
* missing callable()
* missing str.partition
* incorrect compatibility implementation of bin()

Python 2.5-2.5/3.0-3.1 fixes

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/codec/ber/eoo.py
pyasn1/type/base.py
pyasn1/type/char.py
pyasn1/type/univ.py

Up to this point, ASN.1 types' `__init__`, `clone()` and `subtype()` methods had all their arguments explicitly listed in the signature. With time, the list has grown and reached the point of significant  weirdness.
This PR refactors this into way more elegant and hopefully faster `**kwargs`.

ASN.1 types signatures refactoring

---

pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/encoder.py
pyasn1/codec/der/encoder.py
tests/codec/cer/test_encoder.py
tests/codec/der/test_encoder.py

This PR improves https://github.com/etingof/pyasn1/pull/56 in part of recursively handling `OPTIONAL SEQUENCE` field e.g. when field's value is a `CHOICE` or `SEQUENCE OF` type.

Nested optional component encoder fix (take two)

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/type/base.py
pyasn1/type/constraint.py
pyasn1/type/namedtype.py
pyasn1/type/tag.py
pyasn1/type/univ.py
tests/type/test_namedtype.py

This PR moves all lazy initialization into object initializer (eg. `__init__`) for the purpose to avoiding potential collisions when running in a multithreaded environment. The backside is that module loading takes more cycles.
The alternative approach would be to introduce explicit locking, though that seems unnecessary expensive at runtime.

Fixes to threading concurrency issues

---

CHANGES.rst
pyasn1/type/univ.py
tests/type/test_univ.py

This PR unifies SEQUENCE/SET objects behavior (when they lack componentType property and can be configured dynamically) with the ones having rigid components.

Component-less SET/SEQUENCE object to duck-type Python dict

---

CHANGES.rst
pyasn1/__init__.py
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/decoder.py
pyasn1/codec/cer/encoder.py
pyasn1/codec/der/encoder.py
pyasn1/codec/native/decoder.py
pyasn1/codec/native/encoder.py

This change introduces more common API to various codecs and allows passing opaque options to the codecs through the whole call chain.
WARNING: signatures of some undocumented codecs methods changed

Codecs signatures unified and pass **options through

---

CHANGES.rst
pyasn1/codec/ber/encoder.py
pyasn1/codec/native/encoder.py
tests/codec/ber/test_encoder.py

This change fixes a huge inefficiency in how ASN.1 EXPLICIT tags used to be encoded. The codec used to encode tags one-by-one what involved deep-copying the value being encoded.
The reworked algorithm just iterates over tags appending the prepending the encoded blobs at the head of the octet string.

Efficient explicit tags encoding

---

CHANGES.rst
pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/encoder.py
pyasn1/codec/der/encoder.py
tests/codec/der/test_encoder.py

This change hopefully fixes issue https://github.com/etingof/pyasn1/issues/74 and also improves on https://github.com/etingof/pyasn1/issues/11 by enforcing proper length encoding and payload chunking modes whenever particular codec has relevant constraints implied.

ASN.1 codecs to silently enforce proper length/chunk modes

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/debug.py
pyasn1/type/univ.py
tests/base.py
tests/codec/ber/test_decoder.py
tests/codec/ber/test_encoder.py
tests/codec/cer/test_decoder.py
tests/codec/cer/test_encoder.py
tests/codec/der/test_decoder.py
tests/codec/der/test_encoder.py
tests/codec/native/test_decoder.py
tests/codec/native/test_encoder.py
tests/compat/test_binary.py
tests/compat/test_integer.py
tests/compat/test_octets.py
tests/test_debug.py
tests/type/test_char.py
tests/type/test_constraint.py
tests/type/test_namedtype.py
tests/type/test_namedval.py
tests/type/test_tag.py
tests/type/test_univ.py
tests/type/test_useful.py

Apparently, silly bugs like string interpolation accumulate in debugging message over time. This PR is to run all unit tests under full pyasn1 debugging (the actual output is ignored).
Also fixed a couple of crashes found in debug messages.

Run unit tests with full debugging enabled

---

CHANGES.rst
pyasn1/codec/ber/encoder.py
tests/codec/ber/test_encoder.py

As a by-product of this fix, the end-of-octets encoding simplified a great deal by replacing a fully-fledged encoder call with its static outcome. This should improve encoding performance.

Fixed crash on EXPLICIT'ly tagged SEQUENCE component encoding

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/type/base.py
pyasn1/type/univ.py
tests/codec/ber/test_encoder.py
tests/codec/native/test_decoder.py
tests/type/test_univ.py

Previously, ASN.1 objects can be initialized with either `noValue` singleton object or `None` object to indicate ASN.1 schema rather than a schema instance (e.g. a value). The `None` initializer is legacy and should not be widely used.
This PR removes special treatment of the `None` initializer.
Additionally this PR removes default value from ASN.1 `Null` object making it a schema object by default.

Remove None initializer support

---

CHANGES.rst
pyasn1/codec/ber/encoder.py
tests/codec/der/test_encoder.py

This PR fixes a bug which makes this code:
```
s = univ.Sequence(
componentType=namedtype.NamedTypes(
namedtype.OptionalNamedType('null', univ.Null())
)
)
self.s[0] = ''
encoder.encode(s)
```
Producing `(48, 0)` rather than `(48, 2, 5, 0)` e.g. not encoding `Null`. This bug also affects any other simple ASN.1 type whenever being a field of a SET/SEQUENCE and being encoded into an empty octet-stream.

Fix to encoder to omit empty substrate only for constructed types

---

CHANGES.rst
pyasn1/codec/cer/encoder.py
pyasn1/codec/der/encoder.py
tests/codec/cer/test_encoder.py
tests/codec/der/test_encoder.py

This PR fixes the DER/CER encoding of the tagged CHOICE component in part of component ordering. Previously, tagged CHOICE components were ordered in the same way if they were untagged.

DER/CER encoders to respect ordering of tagged CHOICE fields

---

pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/decoder.py
pyasn1/codec/cer/encoder.py
pyasn1/codec/der/decoder.py
pyasn1/codec/der/encoder.py
pyasn1/codec/native/decoder.py
pyasn1/codec/native/encoder.py
pyasn1/error.py
pyasn1/type/base.py
pyasn1/type/char.py
pyasn1/type/univ.py

Due to Sphinx limitations, some `.clone()` and `.subtype()` methods had to be overridden solely for the purpose of maintaining a customized docstring.
This PR removes all those overridden methods and rewords the otherwise different docstrings in a way to apply to all subclass implementations.
Also a handful of RsT markup errors fixed.

Ditched unnecessary .clone/.subtype overrides

---

CHANGES.rst
pyasn1/type/base.py
pyasn1/type/univ.py
tests/type/test_char.py
tests/type/test_univ.py
tests/type/test_useful.py

This PR essentially adds Pickle protocol magic methods to the `NoValue` whitelist. That should at least make pyasn1 not interfering with the Pickle protocol working.

Pickle protocol fixes

---

CHANGES.rst
docs/source/conf.py
pyasn1/type/univ.py
tests/type/test_univ.py

This PR introduces `default` kwarg to the `.getComponentBy*()` methods which is returned instead of the schema object in case the latter is to be returned.
The aim here is to ease migration from older pyasn1 API where `.getComponentBy*()` used to return `None`, then switched to return `noValue` sentinel:
x.getComponentByName('field')  # -> noValue
x.getComponentByName('field', default=None)  # -> None

Add default to .getComponentBy*()

---

CHANGES.rst
pyasn1/type/base.py
pyasn1/type/constraint.py
pyasn1/type/namedtype.py
pyasn1/type/namedval.py
pyasn1/type/tag.py
pyasn1/type/tagmap.py
pyasn1/type/univ.py
tests/type/test_namedtype.py
tests/type/test_tag.py
tests/type/test_univ.py

This PR revamps `__repr__` implementation of ASN.1 types to make them more programmer-friendly and information-rich. At the same time `__repr__` output stopped being `eval()`-compliant.

Refactored ASN.1 types `__repr__` for better readability

---

CHANGES.rst
README.md
docs/source/example-use-case.rst
pyasn1/codec/ber/decoder.py
pyasn1/codec/cer/decoder.py
pyasn1/codec/der/decoder.py
pyasn1/codec/native/decoder.py
pyasn1/codec/native/encoder.py
pyasn1/type/base.py
pyasn1/type/char.py
pyasn1/type/univ.py
tests/type/test_univ.py

This PR moves the `.prettyPrint` ASN.1 types functionality under the `__str__` magic method. The goal is to make ASN.1 schema introspection more intuitive and Pythonic.
The only exception is `OctetString` - `str` on it used to return octet-stream (Py2) or text (Py3) while `.prettyPrint()` used to return hexified contents. This PR does not change this for backward compatibility reasons.

Start `.prettyPrint` deprecation

---

pyasn1/codec/ber/decoder.py
pyasn1/type/univ.py
tests/codec/ber/test_decoder.py
tests/codec/ber/test_encoder.py
tests/type/__main__.py
tests/type/test_opentype.py
tests/type/test_univ.py

This PR disables ASN.1 type check on `Sequence`/`Set` field assignment if the field being assigned is marked as an open type.
In fact, before this PR, one could assign pretty much any type to the untagged `Any` field based on the fact that the untagged and unconstrained `Any` is considered being a supertype to any possible ASN.1 type.
It also adds some more test cases for open type en/decoding.

Relax open type field type check on assignment

---

CHANGES.rst
pyasn1/__init__.py
pyasn1/codec/ber/encoder.py
pyasn1/type/tag.py

0.4.1 [regression](https://github.com/etingof/pyasn1/issues/106)

Fixed bad TagSet initializer at OctetString encoder

---

tests/type/test_univ.py

Not all implementations have to implement getsizeof() and may raise
TypeError instead. Notably, Pypy will always raise TypeError (unless a
default value is provided).

sys.getsizeof() may raise TypeError

---

CHANGES.rst
pyasn1/codec/native/encoder.py

The type map should include all ASN.1 types rather than just ambiguous ones for performance reasons.
Incomplete type ID map triggers building a new TagSet out of the value being encoded. If that value does not have base tags set, that leads to a crash.

Fix native encoder type map

---

docs/source/example-use-case.rst

As [defined in setup.py](https://github.com/kimgr/asn1ate/blob/7ade34d0e3439b8ee0d9d5095a1426bde99f6a48/setup.py#L51), asn1ate define an entry point 'asn1ate' which is probably more straightforward than looking for the full path to the script.

Fix the entrypoint of asn1ate

---

CHANGES.rst
pyasn1/type/univ.py
tests/type/test_univ.py

When SEQUENCE has defaulted component of constructed type, recursively instantiate defaulted component and assign instantiated asn1 object to SEQUENCE field.

Fix defaulted constructed SEQUENCE component initialization

---

pyasn1/type/constraint.py
pyasn1/type/namedval.py

The backslashes seem unnecessary and they're causing deprecation warnings that look like:
pyasn1/type/constraint.py:130: DeprecationWarning: invalid escape sequence \*

Remove invalid escape sequences to get rid of Py3 DeprecationWarning

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
tests/codec/ber/test_decoder.py

The use-case is to make `AnyDecoder` operational when dumping
raw value on error condition is enabled

Fix `AnyDecoder` to accept `TagMap` as `asn1Spec`

---

pyasn1/error.py
pyasn1/type/char.py
pyasn1/type/univ.py

My application can expect either raw bytes or a string in the same underlying ASN1 components. The current exception hierarchy makes this situation basically impossible to handle.
I have added new exceptions specific to string encoding and decoding, and utilized multiple inheritance to ensure that users catching any relevant type of error will still catch these errors. i.e. users that have updated their code to catch `PyAsn1Error` in this situation can continue doing so unaffected, and users that were already catching the `Unicode*Error`s and have not updated will be fixed with this patch.
Also worth noting that Python `.encode()` and `.decode()` will always use the relevant `Unicode*Error` regardless of the passed encoding.

Add specific exceptions for String issues

---

CHANGES.rst
pyasn1/codec/cer/encoder.py
tests/codec/cer/test_encoder.py

- Added support for subseconds CER/DER encoding edge cases in
`GeneralizedTime` codec
- Fixed 3-digit fractional seconds value CER/DER encoding of
`GeneralizedTime`

Improve CER/DER encoding of GeneralizedTime

---

CHANGES.rst
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/type/univ.py
tests/codec/ber/test_decoder.py
tests/codec/ber/test_encoder.py

Add `SET|SEQUENCE OF ANY` encoding support
For example:
```    
AttributeTypeAndValues ::= SEQUENCE {
type OBJECT IDENTIFIER,
values SET OF ANY DEFINED BY type
}
```
This patch adds support of the above ASN.1 syntax to BER/DER/CER
codecs.
It appears that to implement this feature properly, `SetOf`/`SequenceOf`
pyasn1 types need to have `.componentType` wrapped into something
similar to `NamedType` that `Set`/`Sequence` have. That additional
layer would then carry the open type meta information. Without it,
`Sequence`/`Set` codec needs to signal `SetOf`/`SequenceOf` codec
of the open type being processed, which is a slight hack.
A other inconvenience is that when `SetOf`/`SequenceOf` deal with
an open type component, they should not verify types on component
assignment. Without open type …

Add `SET OF ANY` and `SEQUENCE OF ANY` encoding support

---

CHANGES.rst
pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/encoder.py
pyasn1/type/univ.py
tests/codec/ber/test_decoder.py
tests/codec/ber/test_encoder.py
tests/codec/cer/test_decoder.py
tests/codec/cer/test_encoder.py
tests/codec/der/test_decoder.py
tests/codec/der/test_encoder.py
tests/type/test_univ.py

Added a bunch of unit tests to CER/DER codecs covering open types.

Fix CER/DER encoders to respect open types

---

CHANGES.rst
docs/source/pyasn1/type/base/constructedasn1type.rst
docs/source/pyasn1/type/univ/choice.rst
docs/source/pyasn1/type/univ/sequence.rst
docs/source/pyasn1/type/univ/sequenceof.rst
docs/source/pyasn1/type/univ/set.rst
docs/source/pyasn1/type/univ/setof.rst
pyasn1/codec/ber/decoder.py
pyasn1/codec/ber/encoder.py
pyasn1/codec/cer/encoder.py
pyasn1/codec/native/encoder.py
pyasn1/type/base.py
pyasn1/type/univ.py
tests/type/test_univ.py

Added `isInconsistent` property to all constructed types. This property
conceptually replaces `verifySizeSpec` method to serve a more general
purpose e.g. ensuring all required fields are in a good shape. By
default this check invokes subtype constraints verification and is run
by codecs on value de/serialisation.

Add `isInconsistent` property hook to all constructed types

---

tests/codec/ber/test_decoder.py
tests/codec/ber/test_encoder.py

We don't yet know if 3.10 or 4.0 will follow Python 3.9, but whichever it is, it will probably happen in [2020 when Python 3.9 reaches beta](https://www.python.org/dev/peps/pep-0596/#schedule).
There's some tests which check the Python major version is exactly 3. Instead, check it's at least 3.
Found using https://github.com/asottile/flake8-2020:
```console
$ pip install -U flake8-2020
...
$ flake8 --select YTT
./tests/codec/ber/test_decoder.py:489:120: YTT201: `sys.version_info[0] == 3` referenced (python4), use `>=`
./tests/codec/ber/test_decoder.py:494:91: YTT201: `sys.version_info[0] == 3` referenced (python4), use `>=`
./tests/codec/ber/test_decoder.py:499:83: YTT201: `sys.version_info[0] == 3` referenced (python4), use `>=`
./tests/codec/ber/test_encoder.py:439:56: YTT201: …
```

Fix tests for Python 4

---

CHANGES.rst
docs/source/pyasn1/type/base/constructedasn1type.rst
docs/source/pyasn1/type/constraint/contents.rst
docs/source/pyasn1/type/constraint/withcomponents.rst
pyasn1/type/base.py
pyasn1/type/constraint.py
pyasn1/type/univ.py
tests/type/test_constraint.py
tests/type/test_univ.py

Added `WithComponentsConstraint` along with related `ComponentPresentConstraint`
and `ComponentAbsentConstraint` classes to be used with `Sequence`/`Set` types
representing `SET ... WITH COMPONENTS ...` like ASN.1 constructs.

Add `SET ... WITH COMPONENTS ...` ASN.1 construct support

---

CHANGES.rst
pyasn1/type/constraint.py
tests/type/test_constraint.py

Added ability of combining `SingleValueConstraint` and `PermittedAlphabetConstraint` objects into one for proper modeling `FROM ... EXCEPT ...` ASN.1 clause.

Allow combining constraints operating on sets

---

.travis.yml
CHANGES.rst
README.md
pyasn1/compat/integer.py
setup.py
tests/codec/ber/test_decoder.py
tests/type/test_univ.py

Follow on from https://github.com/etingof/pyasn1/pull/131.
* 3.8 was released on 2019-10-14
* 3.4 was EOL on 2019-03-16

Add support for Python 3.8, drop EOL 3.4
